import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SILS Technologies-CI",
  description: "Generated by Yannick Amoikon",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/*Header*/}
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
